CTRL_C = 3         # Ctrl-c
ENTER = 13         # Enter
CTRL_U = 21        # Ctrl+u
CTRL_J = 10        # Ctrl+j
CTRL_K = 11        # Ctrl+k
ESC = 27           # Escape
BACKSPACE =  127   # Backspace
TAB = 9            # Tab
RIGHT = -1     	   # FAKE CODE to abstract away the fact that a multibyte string is needed to represent arrow keys 
DOWN = -2          # same
UP = -3			   # same
LEFT = -4          # same
